### PR TITLE
👷 added m1 mac, mimic, and science builds 🔥 

### PR DESCRIPTION
**Pull request by ninaw04**
co-authored by @Viha123 
co-authored by @PhazonicRidley 
parental supervision by @naterpotatoers

### CODE REVIEW

**Review by naterpotatoers — COMMENTED** [review]
🔥

**Review by PhazonicRidley — APPROVED** [review]
lgtm!

**Review by naterpotatoers — APPROVED** [review]
need more emoji

**Comment by PhazonicRidley** [comment]
> need more emoji

ong no cap fr 🔢 💯 🥇

**Comment by Viha123** [comment]
does not look good to me. need to remove COLONS IN TITLE

**Comment by ninaw04** [comment]
> does not look good to me. need to remove COLONS IN TITLE
SIR YES SIR
RAHH IM SORRY CONTROLS LEAD I WILL DO BETTER NEXT TIME

**Comment by Viha123** [comment]
looks amazing now danke shoen

**Comment by kammce** [comment]
Nice work adding more CI support @ninaw04 ! 🚀

**Pull request merged**
