### PR TITLE
Libhal 2.0 port science

### PR DESCRIPTION
**Pull request by Viha123**
This branch not only ports the entire science subsystem to the updated Libhal-2.0 code architecture. We have also added multiple demos for sensors that may be useful in this science competition or in the future. The demos and drivers included are:
1. Pressure Sensor (@andrew-bork )
2. CO2 Sensor Driver (@MichaelYKersey  and @Kirthika-Ashokkumar )
3. Color Sensor Driver (@Viha123 )
4. LED strips for the Beacon (@andrew-bork )
5. Soil Sensor Driver (@andrew-bork )

### CODE REVIEW

**Review by kammce — CHANGES_REQUESTED** [review]
Why does this commit make changes to the drive code?

**Comment by Viha123** [comment]
I think I initially branched it off of the drive port branch because that had the latest stuff at the time

**Comment by Viha123** [comment]
> Why does this commit make changes to the drive code?

I think I initially branched it off of the drive port branch because that had the latest stuff at the time

**Review by Coreyboy1820 — CHANGES_REQUESTED** [review]
Get this pr to pass all tests before merging. @Viha123

**Comment by Coreyboy1820** [comment]
@kammce are all of these commits from previous branches due to the fact that this was rebased instead of merged when trying to update the branch to main?

**Pull request merged**
